version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://vidhyadharadasul_db_user:Coolrupesh@cluster0.02ou2ml.mongodb.net/trello_db
      - JWT_SECRET=secret123123
      - PORT=3000

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
